name: ⚙️ End-to-end test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
jobs:
  e2e:
    name: ⚙️ End-to-end test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: 🐑 Clone repository
        uses: actions/checkout@v3

      - name: 🦀 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ⛓ Install Node deps
        uses: bahmutov/npm-install@v1

      - name: 🍎 Install operating system dependencies
        run: npx playwright install-deps

      - name: 📦 Restore cached Playwright dependencies
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json')
            }}-${{ hashFiles('**/playwright.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-playwright-i
      - name: 🌐 Install Playwright browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install

      - name: ▶️ Run end-to-end tests
        run: npm run test:e2e
